### ISSUE TITLE
How to modify continuous integration for an application that uses Citus

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#561]
## Why are we implementing it? (sales eng)

People create Rails/Django apps with Citus as the backend and wish to run their integration tests on Circle or Travis. Provide instructions for how to set up a Citus cluster on CI for the application.

## Communication goals (e.g. detailed howto vs orientation)

Example Circle and Travis config files showing the migration from Postgres to Citus.

### Good locations for content in docs structure

New subsection in https://docs.citusdata.com/en/v7.1/migration/transitioning.html#app-migration

**Comment by begriffs** [comment]
Circle config file inspiration:

```yaml
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: YOUR BASE IMAGE
        environment:
          PGUSER: postgres
      - image: citusdata/citus:7.1.0
      - image: citusdata/citus:7.1.0
        environment:
          PGPORT: 5433
      - image: citusdata/citus:7.1.0
        environment:
          PGPORT: 5434
    steps:        
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: dockerize -wait tcp://localhost:5433 -timeout 1m
      - run: dockerize -wait tcp://localhost:5434 -timeout 1m

      - run:
          name: Add workers
          command: |
            psql -c "SELECT * from master_add_node('localhost', 5433);";
            psql -c "SELECT * from master_add_node('localhost', 5434);";
```

Simply starts a coordinator and two workers, and the app can then connect to 5432.
