### ISSUE TITLE
Content forced below menu

### ISSUE THREAD

**Issue by begriffs** [citusdata/citus_docs#96]
The manual cloudformation template section clears the navigation menu and appears too far down the page.

https://docs.citusdata.com/en/v5.1/installation/multi_machine_aws.html#manual-cloudformation-deployment

**Comment by begriffs** [comment]
Looks like it happens because of

```css
.wy-btn-group:before, .wy-btn-group:after {
  display: table;
}
```

Have to see what else that affects and if it can be outright removed.
